from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QApplication, QMessageBox, QFileDialog, QCheckBox
# from PyQt5.QtWidgets import QApplication, QComboBox, QLineEdit, QWidget

from pytube import YouTube
import urllib.request

import re
import requests
import os
os.environ["PAFY_BACKEND"] = "internal"
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")

        Form.setFixedSize(570, 371)

        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(7)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAcceptDrops(False)
        Form.setStyleSheet("QProgressBar:horizontal {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    text-align: center;\n"
                           "    padding: 1px;\n"
                           "    background: #201F1F;\n"
                           "}\n"
                           "QProgressBar::chunk:horizontal {\n"
                           "    background-color: qlineargradient(spread:reflect, x1:1, y1:0.545, x2:1, y2:0, stop:0 rgba(28, 66, 111, 255), stop:1 rgba(37, 87, 146, 255));\n"
                           "}\n"
                           "\n"
                           "QToolTip\n"
                           "{\n"
                           "    border: 1px solid #3A3939;\n"
                           "    background-color: rgb(90, 102, 117);;\n"
                           "    color: white;\n"
                           "    padding: 1px;\n"
                           "    opacity: 200;\n"
                           "}\n"
                           "\n"
                           "QWidget\n"
                           "{\n"
                           "    color: silver;\n"
                           "    background-color: #302F7F;\n"
                           "    selection-background-color:#3d8ec9;\n"
                           "    selection-color: black;\n"
                           "    background-clip: border;\n"
                           "    border-image: none;\n"
                           "    outline: 0;\n"
                           "}\n"
                           "\n"
                           "QWidget:item:hover\n"
                           "{\n"
                           "    background-color: #78879b;\n"
                           "    color: black;\n"
                           "}\n"
                           "\n"
                           "QWidget:item:selected\n"
                           "{\n"
                           "    background-color: #3d8ec9;\n"
                           "}\n"
                           "\n"
                           "QCheckBox\n"
                           "{\n"
                           "    spacing: 5px;\n"
                           "    outline: none;\n"
                           "    color: #bbb;\n"
                           "    margin-bottom: 2px;\n"
                           "}\n"
                           "\n"
                           "QCheckBox:disabled\n"
                           "{\n"
                           "    color: #777777;\n"
                           "}\n"
                           "QCheckBox::indicator,\n"
                           "QGroupBox::indicator\n"
                           "{\n"
                           "    width: 18px;\n"
                           "    height: 18px;\n"
                           "}\n"
                           "QGroupBox::indicator\n"
                           "{\n"
                           "    margin-left: 2px;\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:unchecked,\n"
                           "QCheckBox::indicator:unchecked:hover,\n"
                           "QGroupBox::indicator:unchecked,\n"
                           "QGroupBox::indicator:unchecked:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_unchecked.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:unchecked:focus,\n"
                           "QCheckBox::indicator:unchecked:pressed,\n"
                           "QGroupBox::indicator:unchecked:focus,\n"
                           "QGroupBox::indicator:unchecked:pressed\n"
                           "{\n"
                           "  border: none;\n"
                           "    image: url(:/dark_blue/img/checkbox_unchecked_focus.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:checked,\n"
                           "QCheckBox::indicator:checked:hover,\n"
                           "QGroupBox::indicator:checked,\n"
                           "QGroupBox::indicator:checked:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_checked.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:checked:focus,\n"
                           "QCheckBox::indicator:checked:pressed,\n"
                           "QGroupBox::indicator:checked:focus,\n"
                           "QGroupBox::indicator:checked:pressed\n"
                           "{\n"
                           "  border: none;\n"
                           "    image: url(:/dark_blue/img/checkbox_checked_focus.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:indeterminate,\n"
                           "QCheckBox::indicator:indeterminate:hover,\n"
                           "QCheckBox::indicator:indeterminate:pressed\n"
                           "QGroupBox::indicator:indeterminate,\n"
                           "QGroupBox::indicator:indeterminate:hover,\n"
                           "QGroupBox::indicator:indeterminate:pressed\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_indeterminate.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:indeterminate:focus,\n"
                           "QGroupBox::indicator:indeterminate:focus\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_indeterminate_focus.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:checked:disabled,\n"
                           "QGroupBox::indicator:checked:disabled\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_checked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:unchecked:disabled,\n"
                           "QGroupBox::indicator:unchecked:disabled\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/checkbox_unchecked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton\n"
                           "{\n"
                           "    spacing: 5px;\n"
                           "    outline: none;\n"
                           "    color: #bbb;\n"
                           "    margin-bottom: 2px;\n"
                           "}\n"
                           "\n"
                           "QRadioButton:disabled\n"
                           "{\n"
                           "    color: #777777;\n"
                           "}\n"
                           "QRadioButton::indicator\n"
                           "{\n"
                           "    width: 21px;\n"
                           "    height: 21px;\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:unchecked,\n"
                           "QRadioButton::indicator:unchecked:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/radio_unchecked.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:unchecked:focus,\n"
                           "QRadioButton::indicator:unchecked:pressed\n"
                           "{\n"
                           "  border: none;\n"
                           "  outline: none;\n"
                           "    image: url(:/dark_blue/img/radio_unchecked_focus.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:checked,\n"
                           "QRadioButton::indicator:checked:hover\n"
                           "{\n"
                           "  border: none;\n"
                           "  outline: none;\n"
                           "    image: url(:/dark_blue/img/radio_checked.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:checked:focus,\n"
                           "QRadioButton::indicato::menu-arrowr:checked:pressed\n"
                           "{\n"
                           "  border: none;\n"
                           "  outline: none;\n"
                           "    image: url(:/dark_blue/img/radio_checked_focus.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:indeterminate,\n"
                           "QRadioButton::indicator:indeterminate:hover,\n"
                           "QRadioButton::indicator:indeterminate:pressed\n"
                           "{\n"
                           "        image: url(:/dark_blue/img/radio_indeterminate.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:checked:disabled\n"
                           "{\n"
                           "  outline: none;\n"
                           "  image: url(:/dark_blue/img/radio_checked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:unchecked:disabled\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/radio_unchecked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QMenuBar\n"
                           "{\n"
                           "    background-color: #302F2F;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item\n"
                           "{\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item:selected\n"
                           "{\n"
                           "    background: transparent;\n"
                           "    border: 1px solid #3A3939;\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item:pressed\n"
                           "{\n"
                           "    border: 1px solid #3A3939;\n"
                           "    background-color: #3d8ec9;\n"
                           "    color: black;\n"
                           "    margin-bottom:-1px;\n"
                           "    padding-bottom:1px;\n"
                           "}\n"
                           "\n"
                           "QMenu\n"
                           "{\n"
                           "    border: 1px solid #3A3939;\n"
                           "    color: silver;\n"
                           "    margin: 1px;\n"
                           "}\n"
                           "\n"
                           "QMenu::icon\n"
                           "{\n"
                           "    margin: 1px;\n"
                           "}\n"
                           "\n"
                           "QMenu::item\n"
                           "{\n"
                           "    padding: 2px 2px 2px 25px;\n"
                           "    margin-left: 5px;\n"
                           "    border: 1px solid transparent; /* reserve space for selection border */\n"
                           "}\n"
                           "\n"
                           "QMenu::item:selected\n"
                           "{\n"
                           "    color: black;\n"
                           "}\n"
                           "\n"
                           "QMenu::separator {\n"
                           "    height: 2px;\n"
                           "    background: lightblue;\n"
                           "    margin-left: 10px;\n"
                           "    margin-right: 5px;\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator {\n"
                           "    width: 16px;\n"
                           "    height: 16px;\n"
                           "}\n"
                           "\n"
                           "/* non-exclusive indicator = check box style indicator\n"
                           "   (see QActionGroup::setExclusive) */\n"
                           "QMenu::indicator:non-exclusive:unchecked {\n"
                           "    image: url(:/dark_blue/img/checkbox_unchecked.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:non-exclusive:unchecked:selected {\n"
                           "    image: url(:/dark_blue/img/checkbox_unchecked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:non-exclusive:checked {\n"
                           "    image: url(:/dark_blue/img/checkbox_checked.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:non-exclusive:checked:selected {\n"
                           "    image: url(:/dark_blue/img/checkbox_checked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
                           "QMenu::indicator:exclusive:unchecked {\n"
                           "    image: url(:/dark_blue/img/radio_unchecked.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:exclusive:unchecked:selected {\n"
                           "    image: url(:/dark_blue/img/radio_unchecked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:exclusive:checked {\n"
                           "    image: url(:/dark_blue/img/radio_checked.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::indicator:exclusive:checked:selected {\n"
                           "    image: url(:/dark_blue/img/radio_checked_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::right-arrow {\n"
                           "    margin: 5px;\n"
                           "    image: url(:/dark_blue/img/right_arrow.png)\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QWidget:disabled\n"
                           "{\n"
                           "    color: #808080;\n"
                           "    background-color: #302F2F;\n"
                           "}\n"
                           "\n"
                           "QAbstractItemView\n"
                           "{\n"
                           "    alternate-background-color: #3A3939;\n"
                           "    color: silver;\n"
                           "    border: 1px solid 3A3939;\n"
                           "    border-radius: 2px;\n"
                           "    padding: 1px;\n"
                           "}\n"
                           "\n"
                           "QWidget:focus, QMenuBar:focus\n"
                           "{\n"
                           "    border: 1px solid #78879b;\n"
                           "}\n"
                           "\n"
                           "QTabWidget:focus, QCheckBox:focus, QRadioButton:focus, QSlider:focus\n"
                           "{\n"
                           "    border: none;\n"
                           "}\n"
                           "\n"
                           "QLineEdit\n"
                           "{\n"
                           "    background-color: #201F1F;\n"
                           "    padding: 2px;\n"
                           "    border-style: solid;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    border-radius: 2px;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QGroupBox {\n"
                           "    border:1px solid #3A3939;\n"
                           "    border-radius: 2px;\n"
                           "    margin-top: 20px;\n"
                           "    background-color: #302F2F;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QGroupBox::title {\n"
                           "    subcontrol-origin: margin;\n"
                           "    subcontrol-position: top center;\n"
                           "    padding-left: 10px;\n"
                           "    padding-right: 10px;\n"
                           "    padding-top: 10px;\n"
                           "}\n"
                           "\n"
                           "QAbstractScrollArea\n"
                           "{\n"
                           "    border-radius: 2px;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    background-color: transparent;\n"
                           "}\n"
                           "\n"
                           "QScrollBar:horizontal\n"
                           "{\n"
                           "    height: 15px;\n"
                           "    margin: 3px 15px 3px 15px;\n"
                           "    border: 1px transparent #2A2929;\n"
                           "    border-radius: 4px;\n"
                           "    background-color: #2A2929;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::handle:horizontal\n"
                           "{\n"
                           "    background-color: #605F5F;\n"
                           "    min-width: 5px;\n"
                           "    border-radius: 4px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-line:horizontal\n"
                           "{\n"
                           "    margin: 0px 3px 0px 3px;\n"
                           "    border-image: url(:/dark_blue/img/right_arrow_disabled.png);\n"
                           "    width: 10px;\n"
                           "    height: 10px;\n"
                           "    subcontrol-position: right;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::sub-line:horizontal\n"
                           "{\n"
                           "    margin: 0px 3px 0px 3px;\n"
                           "    border-image: url(:/dark_blue/img/left_arrow_disabled.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: left;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
                           "{\n"
                           "    border-image: url(:/dark_blue/img/right_arrow.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: right;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
                           "{\n"
                           "    border-image: url(:/dark_blue/img/left_arrow.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: left;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
                           "{\n"
                           "    background: none;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                           "{\n"
                           "    background: none;\n"
                           "}\n"
                           "\n"
                           "QScrollBar:vertical\n"
                           "{\n"
                           "    background-color: #2A2929;\n"
                           "    width: 15px;\n"
                           "    margin: 15px 3px 15px 3px;\n"
                           "    border: 1px transparent #2A2929;\n"
                           "    border-radius: 4px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::handle:vertical\n"
                           "{\n"
                           "    background-color: #605F5F;\n"
                           "    min-height: 5px;\n"
                           "    border-radius: 4px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::sub-line:vertical\n"
                           "{\n"
                           "    margin: 3px 0px 3px 0px;\n"
                           "    border-image: url(:/dark_blue/img/up_arrow_disabled.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: top;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-line:vertical\n"
                           "{\n"
                           "    margin: 3px 0px 3px 0px;\n"
                           "    border-image: url(:/dark_blue/img/down_arrow_disabled.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: bottom;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
                           "{\n"
                           "\n"
                           "    border-image: url(:/dark_blue/img/up_arrow.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: top;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
                           "{\n"
                           "    border-image: url(:/dark_blue/img/down_arrow.png);\n"
                           "    height: 10px;\n"
                           "    width: 10px;\n"
                           "    subcontrol-position: bottom;\n"
                           "    subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                           "{\n"
                           "    background: none;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                           "{\n"
                           "    background: none;\n"
                           "}\n"
                           "\n"
                           "QTextEdit\n"
                           "{\n"
                           "    background-color: #201F1F;\n"
                           "    color: silver;\n"
                           "    border: 1px solid #3A3939;\n"
                           "}\n"
                           "\n"
                           "QPlainTextEdit\n"
                           "{\n"
                           "    background-color: #201F1F;;\n"
                           "    color: silver;\n"
                           "    border-radius: 2px;\n"
                           "    border: 1px solid #3A3939;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section\n"
                           "{\n"
                           "    background-color: #3A3939;\n"
                           "    color: silver;\n"
                           "    padding-left: 4px;\n"
                           "    border: 1px solid #6c6c6c;\n"
                           "}\n"
                           "\n"
                           "QSizeGrip {\n"
                           "    image: url(:/dark_blue/img/sizegrip.png);\n"
                           "    width: 12px;\n"
                           "    height: 12px;\n"
                           "}\n"
                           "\n"
                           "QMainWindow\n"
                           "{\n"
                           "    background-color: #302F2F;\n"
                           "\n"
                           "}\n"
                           "\n"
                           "QMainWindow::separator\n"
                           "{\n"
                           "    background-color: #302F2F;\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    spacing: 2px;\n"
                           "    border: 1px dashed #3A3939;\n"
                           "}\n"
                           "\n"
                           "QMainWindow::separator:hover\n"
                           "{\n"
                           "\n"
                           "    background-color: #787876;\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    spacing: 2px;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QMenu::separator\n"
                           "{\n"
                           "    height: 1px;\n"
                           "    background-color: #3A3939;\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    margin-left: 10px;\n"
                           "    margin-right: 5px;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QFrame\n"
                           "{\n"
                           "    border-radius: 2px;\n"
                           "    border: 1px solid #444;\n"
                           "}\n"
                           "\n"
                           "QFrame[frameShape=\"0\"]\n"
                           "{\n"
                           "    border-radius: 2px;\n"
                           "    border: 1px transparent #444;\n"
                           "}\n"
                           "\n"
                           "QStackedWidget\n"
                           "{\n"
                           "    background-color: #302F2F;\n"
                           "    border: 1px transparent black;\n"
                           "}\n"
                           "\n"
                           "QToolBar {\n"
                           "    border: 1px transparent #393838;\n"
                           "    background: 1px solid #302F2F;\n"
                           "    font-weight: bold;\n"
                           "}\n"
                           "\n"
                           "QToolBar::handle:horizontal {\n"
                           "    image: url(:/dark_blue/img/Hmovetoolbar.png);\n"
                           "}\n"
                           "QToolBar::handle:vertical {\n"
                           "    image: url(:/dark_blue/img/Vmovetoolbar.png);\n"
                           "}\n"
                           "QToolBar::separator:horizontal {\n"
                           "    image: url(:/dark_blue/img/Hsepartoolbar.png);\n"
                           "}\n"
                           "QToolBar::separator:vertical {\n"
                           "    image: url(:/dark_blue/img/Vsepartoolbars.png);\n"
                           "}\n"
                           "\n"
                           "QPushButton\n"
                           "{\n"
                           "    color: silver;\n"
                           "    background-color: #302F2F;\n"
                           "    border-width: 2px;\n"
                           "    border-color: #4A4949;\n"
                           "    border-style: solid;\n"
                           "    padding-top: 2px;\n"
                           "    padding-bottom: 2px;\n"
                           "    padding-left: 10px;\n"
                           "    padding-right: 10px;\n"
                           "    border-radius: 4px;\n"
                           "    /* outline: none; */\n"
                           "    /* min-width: 40px; */\n"
                           "}\n"
                           "\n"
                           "QPushButton:disabled\n"
                           "{\n"
                           "    background-color: #302F2F;\n"
                           "    border-width: 2px;\n"
                           "    border-color: #3A3939;\n"
                           "    border-style: solid;\n"
                           "    padding-top: 2px;\n"
                           "    padding-bottom: 2px;\n"
                           "    padding-left: 10px;\n"
                           "    padding-right: 10px;\n"
                           "    /*border-radius: 2px;*/\n"
                           "    color: #808080;\n"
                           "}\n"
                           "\n"
                           "QPushButton:focus {\n"
                           "    background-color: #3d8ec9;\n"
                           "    color: white;\n"
                           "}\n"
                           "\n"
                           "QComboBox\n"
                           "{\n"
                           "    selection-background-color: #3d8ec9;\n"
                           "    background-color: #201F1F;\n"
                           "    border-style: solid;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    border-radius: 2px;\n"
                           "    padding: 2px;\n"
                           "    min-width: 75px;\n"
                           "}\n"
                           "\n"
                           "QPushButton:checked{\n"
                           "    background-color: #4A4949;\n"
                           "    border-color: #6A6969;\n"
                           "}\n"
                           "\n"
                           "QPushButton:hover {\n"
                           "    border: 2px solid #78879b;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QComboBox:hover, QAbstractSpinBox:hover,QLineEdit:hover,QTextEdit:hover,QPlainTextEdit:hover,QAbstractView:hover,QTreeView:hover\n"
                           "{\n"
                           "    border: 1px solid #78879b;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QComboBox:on\n"
                           "{\n"
                           "    background-color: #626873;\n"
                           "    padding-top: 3px;\n"
                           "    padding-left: 4px;\n"
                           "    selection-background-color: #4a4a4a;\n"
                           "}\n"
                           "\n"
                           "QComboBox QAbstractItemView\n"
                           "{\n"
                           "    background-color: #201F1F;\n"
                           "    border-radius: 2px;\n"
                           "    border: 1px solid #444;\n"
                           "    selection-background-color: #3d8ec9;\n"
                           "    color: silver;\n"
                           "}\n"
                           "\n"
                           "QComboBox::drop-down\n"
                           "{\n"
                           "    subcontrol-origin: padding;\n"
                           "    subcontrol-position: top right;\n"
                           "    width: 15px;\n"
                           "\n"
                           "    border-left-width: 0px;\n"
                           "    border-left-color: darkgray;\n"
                           "    border-left-style: solid;\n"
                           "    border-top-right-radius: 3px;\n"
                           "    border-bottom-right-radius: 3px;\n"
                           "}\n"
                           "\n"
                           "QComboBox::down-arrow\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/down_arrow_disabled.png);\n"
                           "}\n"
                           "\n"
                           "QComboBox::down-arrow:on, QComboBox::down-arrow:hover,\n"
                           "QComboBox::down-arrow:focus\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/down_arrow.png);\n"
                           "}\n"
                           "\n"
                           "QPushButton:pressed\n"
                           "{\n"
                           "    background-color: #484846;\n"
                           "}\n"
                           "\n"
                           "QAbstractSpinBox {\n"
                           "    padding-top: 2px;\n"
                           "    padding-bottom: 2px;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    background-color: #201F1F;\n"
                           "    color: silver;\n"
                           "    border-radius: 2px;\n"
                           "    min-width: 75px;\n"
                           "}\n"
                           "\n"
                           "QAbstractSpinBox:up-button\n"
                           "{\n"
                           "    background-color: transparent;\n"
                           "    subcontrol-origin: border;\n"
                           "    subcontrol-position: top right;\n"
                           "}\n"
                           "\n"
                           "QAbstractSpinBox:down-button\n"
                           "{\n"
                           "    background-color: transparent;\n"
                           "    subcontrol-origin: border;\n"
                           "    subcontrol-position: bottom right;\n"
                           "}\n"
                           "\n"
                           "QAbstractSpinBox::up-arrow,QAbstractSpinBox::up-arrow:disabled,QAbstractSpinBox::up-arrow:off {\n"
                           "    image: url(:/dark_blue/img/up_arrow_disabled.png);\n"
                           "    width: 10px;\n"
                           "    height: 10px;\n"
                           "}\n"
                           "QAbstractSpinBox::up-arrow:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/up_arrow.png);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QAbstractSpinBox::down-arrow,QAbstractSpinBox::down-arrow:disabled,QAbstractSpinBox::down-arrow:off\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/down_arrow_disabled.png);\n"
                           "    width: 10px;\n"
                           "    height: 10px;\n"
                           "}\n"
                           "QAbstractSpinBox::down-arrow:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/down_arrow.png);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QLabel\n"
                           "{\n"
                           "    border: 0px solid black;\n"
                           "}\n"
                           "\n"
                           "QTabWidget{\n"
                           "    border: 1px transparent black;\n"
                           "}\n"
                           "\n"
                           "QTabWidget::pane {\n"
                           "    border: 1px solid #444;\n"
                           "    border-radius: 3px;\n"
                           "    padding: 3px;\n"
                           "}\n"
                           "\n"
                           "QTabBar\n"
                           "{\n"
                           "    qproperty-drawBase: 0;\n"
                           "    left: 5px; /* move to the right by 5px */\n"
                           "}\n"
                           "\n"
                           "QTabBar:focus\n"
                           "{\n"
                           "    border: 0px transparent black;\n"
                           "}\n"
                           "\n"
                           "QTabBar::close-button  {\n"
                           "    image: url(:/dark_blue/img/close.png);\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "QTabBar::close-button:hover\n"
                           "{\n"
                           "    image: url(:/dark_blue/img/close-hover.png);\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "QTabBar::close-button:pressed {\n"
                           "    image: url(:/dark_blue/img/close-pressed.png);\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "/* TOP TABS */\n"
                           "QTabBar::tab:top {\n"
                           "    color: #b1b1b1;\n"
                           "    border: 1px solid #4A4949;\n"
                           "    border-bottom: 1px transparent black;\n"
                           "    background-color: #302F2F;\n"
                           "    padding: 5px;\n"
                           "    border-top-left-radius: 2px;\n"
                           "    border-top-right-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:top:!selected\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #201F1F;\n"
                           "    border: 1px transparent #4A4949;\n"
                           "    border-bottom: 1px transparent #4A4949;\n"
                           "    border-top-left-radius: 0px;\n"
                           "    border-top-right-radius: 0px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:top:!selected:hover {\n"
                           "    background-color: #48576b;\n"
                           "}\n"
                           "\n"
                           "/* BOTTOM TABS */\n"
                           "QTabBar::tab:bottom {\n"
                           "    color: #b1b1b1;\n"
                           "    border: 1px solid #4A4949;\n"
                           "    border-top: 1px transparent black;\n"
                           "    background-color: #302F2F;\n"
                           "    padding: 5px;\n"
                           "    border-bottom-left-radius: 2px;\n"
                           "    border-bottom-right-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:bottom:!selected\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #201F1F;\n"
                           "    border: 1px transparent #4A4949;\n"
                           "    border-top: 1px transparent #4A4949;\n"
                           "    border-bottom-left-radius: 0px;\n"
                           "    border-bottom-right-radius: 0px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:bottom:!selected:hover {\n"
                           "    background-color: #78879b;\n"
                           "}\n"
                           "\n"
                           "/* LEFT TABS */\n"
                           "QTabBar::tab:left {\n"
                           "    color: #b1b1b1;\n"
                           "    border: 1px solid #4A4949;\n"
                           "    border-left: 1px transparent black;\n"
                           "    background-color: #302F2F;\n"
                           "    padding: 5px;\n"
                           "    border-top-right-radius: 2px;\n"
                           "    border-bottom-right-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:left:!selected\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #201F1F;\n"
                           "    border: 1px transparent #4A4949;\n"
                           "    border-right: 1px transparent #4A4949;\n"
                           "    border-top-right-radius: 0px;\n"
                           "    border-bottom-right-radius: 0px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:left:!selected:hover {\n"
                           "    background-color: #48576b;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "/* RIGHT TABS */\n"
                           "QTabBar::tab:right {\n"
                           "    color: #b1b1b1;\n"
                           "    border: 1px solid #4A4949;\n"
                           "    border-right: 1px transparent black;\n"
                           "    background-color: #302F2F;\n"
                           "    padding: 5px;\n"
                           "    border-top-left-radius: 2px;\n"
                           "    border-bottom-left-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:right:!selected\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #201F1F;\n"
                           "    border: 1px transparent #4A4949;\n"
                           "    border-right: 1px transparent #4A4949;\n"
                           "    border-top-left-radius: 0px;\n"
                           "    border-bottom-left-radius: 0px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:right:!selected:hover {\n"
                           "    background-color: #48576b;\n"
                           "}\n"
                           "\n"
                           "QTabBar QToolButton::right-arrow:enabled {\n"
                           "     image: url(:/dark_blue/img/right_arrow.png);\n"
                           " }\n"
                           "\n"
                           " QTabBar QToolButton::left-arrow:enabled {\n"
                           "     image: url(:/dark_blue/img/left_arrow.png);\n"
                           " }\n"
                           "\n"
                           "QTabBar QToolButton::right-arrow:disabled {\n"
                           "     image: url(:/dark_blue/img/right_arrow_disabled.png);\n"
                           " }\n"
                           "\n"
                           " QTabBar QToolButton::left-arrow:disabled {\n"
                           "     image: url(:/dark_blue/img/left_arrow_disabled.png);\n"
                           " }\n"
                           "\n"
                           "\n"
                           "QDockWidget {\n"
                           "    border: 1px solid #403F3F;\n"
                           "    titlebar-close-icon: url(:/dark_blue/img/close.png);\n"
                           "    titlebar-normal-icon: url(:/dark_blue/img/undock.png);\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button, QDockWidget::float-button {\n"
                           "    border: 1px solid transparent;\n"
                           "    border-radius: 2px;\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button:hover, QDockWidget::float-button:hover {\n"
                           "    background: rgba(255, 255, 255, 10);\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button:pressed, QDockWidget::float-button:pressed {\n"
                           "    padding: 1px -1px -1px 1px;\n"
                           "    background: rgba(255, 255, 255, 10);\n"
                           "}\n"
                           "\n"
                           "QTreeView, QListView, QTextBrowser, AtLineEdit, AtLineEdit::hover {\n"
                           "    border: 1px solid #444;\n"
                           "    background-color: silver;\n"
                           "    border-radius: 3px;\n"
                           "    margin-left: 3px;\n"
                           "    color: black;\n"
                           "}\n"
                           "\n"
                           "QTreeView:branch:selected, QTreeView:branch:hover {\n"
                           "    background: url(:/dark_blue/img/transparent.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:has-siblings:!adjoins-item {\n"
                           "    border-image: url(:/dark_blue/img/transparent.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:has-siblings:adjoins-item {\n"
                           "    border-image: url(:/dark_blue/img/transparent.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
                           "    border-image: url(:/dark_blue/img/transparent.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:has-children:!has-siblings:closed,\n"
                           "QTreeView::branch:closed:has-children:has-siblings {\n"
                           "    image: url(:/dark_blue/img/branch_closed.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:open:has-children:!has-siblings,\n"
                           "QTreeView::branch:open:has-children:has-siblings  {\n"
                           "    image: url(:/dark_blue/img/branch_open.png);\n"
                           "}\n"
                           "\n"
                           "QTreeView::branch:has-children:!has-siblings:closed:hover,\n"
                           "QTreeView::branch:closed:has-children:has-siblings:hover {\n"
                           "    image: url(:/dark_blue/img/branch_closed-on.png);\n"
                           "    }\n"
                           "\n"
                           "QTreeView::branch:open:has-children:!has-siblings:hover,\n"
                           "QTreeView::branch:open:has-children:has-siblings:hover  {\n"
                           "    image: url(:/dark_blue/img/branch_open-on.png);\n"
                           "    }\n"
                           "\n"
                           "QListView::item:!selected:hover, QListView::item:!selected:hover, QTreeView::item:!selected:hover  {\n"
                           "    background: rgba(0, 0, 0, 0);\n"
                           "    outline: 0;\n"
                           "    color: #FFFFFF\n"
                           "}\n"
                           "\n"
                           "QListView::item:selected:hover, QListView::item:selected:hover, QTreeView::item:selected:hover  {\n"
                           "    background: #3d8ec9;\n"
                           "    color: #FFFFFF;\n"
                           "}\n"
                           "\n"
                           "QSlider::groove:horizontal {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    height: 8px;\n"
                           "    background: #201F1F;\n"
                           "    margin: 2px 0;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::handle:horizontal {\n"
                           "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
                           "      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 14px;\n"
                           "    height: 14px;\n"
                           "    margin: -4px 0;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::groove:vertical {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 8px;\n"
                           "    background: #201F1F;\n"
                           "    margin: 0 0px;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::handle:vertical {\n"
                           "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
                           "    stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 14px;\n"
                           "    height: 14px;\n"
                           "    margin: 0 -4px;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QToolButton {\n"
                           "    /*  background-color: transparent; */\n"
                           "    border: 2px transparent #4A4949;\n"
                           "    border-radius: 4px;\n"
                           "    background-color: dimgray;\n"
                           "    margin: 2px;\n"
                           "    padding: 2px;\n"
                           "}\n"
                           "\n"
                           "QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
                           " padding-right: 20px; /* make way for the popup button */\n"
                           " border: 2px transparent #4A4949;\n"
                           " border-radius: 4px;\n"
                           "}\n"
                           "\n"
                           "QToolButton[popupMode=\"2\"] { /* only for InstantPopup */\n"
                           " padding-right: 10px; /* make way for the popup button */\n"
                           " border: 2px transparent #4A4949;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QToolButton:hover, QToolButton::menu-button:hover {\n"
                           "    border: 2px solid #78879b;\n"
                           "}\n"
                           "\n"
                           "QToolButton:checked, QToolButton:pressed,\n"
                           "    QToolButton::menu-button:pressed {\n"
                           "    background-color: #4A4949;\n"
                           "    border: 2px solid #78879b;\n"
                           "}\n"
                           "\n"
                           "/* the subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
                           "QToolButton::menu-indicator {\n"
                           "    image: url(:/dark_blue/img/down_arrow.png);\n"
                           "    top: -7px; left: -2px; /* shift it a bit */\n"
                           "}\n"
                           "\n"
                           "/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
                           "QToolButton::menu-button {\n"
                           "    border: 1px transparent #4A4949;\n"
                           "    border-top-right-radius: 6px;\n"
                           "    border-bottom-right-radius: 6px;\n"
                           "    /* 16px width + 4px for border = 20px allocated above */\n"
                           "    width: 16px;\n"
                           "    outline: none;\n"
                           "}\n"
                           "\n"
                           "QToolButton::menu-arrow {\n"
                           "    image: url(:/dark_blue/img/down_arrow.png);\n"
                           "}\n"
                           "\n"
                           "QToolButton::menu-arrow:open {\n"
                           "    top: 1px; left: 1px; /* shift it a bit */\n"
                           "    border: 1px solid #3A3939;\n"
                           "}\n"
                           "\n"
                           "QPushButton::menu-indicator  {\n"
                           "    subcontrol-origin: padding;\n"
                           "    subcontrol-position: bottom right;\n"
                           "    left: 4px;\n"
                           "}\n"
                           "\n"
                           "QTableView\n"
                           "{\n"
                           "    border: 1px solid #444;\n"
                           "    gridline-color: #6c6c6c;\n"
                           "    background-color: #201F1F;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QTableView, QHeaderView\n"
                           "{\n"
                           "    border-radius: 0px;\n"
                           "}\n"
                           "\n"
                           "QTableView::item:pressed, QListView::item:pressed, QTreeView::item:pressed  {\n"
                           "    background: #78879b;\n"
                           "    color: #FFFFFF;\n"
                           "}\n"
                           "\n"
                           "QTableView::item:selected:active, QTreeView::item:selected:active, QListView::item:selected:active  {\n"
                           "    background: #3d8ec9;\n"
                           "    color: #FFFFFF;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QHeaderView\n"
                           "{\n"
                           "    border: 1px transparent;\n"
                           "    border-radius: 2px;\n"
                           "    margin: 0px;\n"
                           "    padding: 0px;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section  {\n"
                           "    background-color: #3A3939;\n"
                           "    color: silver;\n"
                           "    padding: 4px;\n"
                           "    border: 1px solid #6c6c6c;\n"
                           "    border-radius: 0px;\n"
                           "    text-align: center;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section::vertical::first, QHeaderView::section::vertical::only-one\n"
                           "{\n"
                           "    border-top: 1px solid #6c6c6c;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section::vertical\n"
                           "{\n"
                           "    border-top: transparent;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one\n"
                           "{\n"
                           "    border-left: 1px solid #6c6c6c;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section::horizontal\n"
                           "{\n"
                           "    border-left: transparent;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QHeaderView::section:checked\n"
                           " {\n"
                           "    color: white;\n"
                           "    background-color: #5A5959;\n"
                           " }\n"
                           "\n"
                           " /* style the sort indicator */\n"
                           "QHeaderView::down-arrow {\n"
                           "    image: url(:/dark_blue/img/down_arrow.png);\n"
                           "}\n"
                           "\n"
                           "QHeaderView::up-arrow {\n"
                           "    image: url(:/dark_blue/img/up_arrow.png);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QTableCornerButton::section {\n"
                           "    background-color: #3A3939;\n"
                           "    border: 1px solid #3A3939;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QToolBox  {\n"
                           "    padding: 3px;\n"
                           "    border: 1px transparent black;\n"
                           "}\n"
                           "\n"
                           "QToolBox::tab {\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #302F2F;\n"
                           "    border: 1px solid #4A4949;\n"
                           "    border-bottom: 1px transparent #302F2F;\n"
                           "    border-top-left-radius: 5px;\n"
                           "    border-top-right-radius: 5px;\n"
                           "}\n"
                           "\n"
                           " QToolBox::tab:selected { /* italicize selected tabs */\n"
                           "    font: italic;\n"
                           "    background-color: #302F2F;\n"
                           "    border-color: #3d8ec9;\n"
                           " }\n"
                           "\n"
                           "QStatusBar::item {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    border-radius: 2px;\n"
                           " }\n"
                           "\n"
                           "\n"
                           "QFrame[height=\"3\"], QFrame[width=\"3\"] {\n"
                           "    background-color: #AAA;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QSplitter::handle {\n"
                           "    border: 1px dashed #3A3939;\n"
                           "}\n"
                           "\n"
                           "QSplitter::handle:hover {\n"
                           "    background-color: #787876;\n"
                           "    border: 1px solid #3A3939;\n"
                           "}\n"
                           "\n"
                           "QSplitter::handle:horizontal {\n"
                           "    width: 1px;\n"
                           "}\n"
                           "\n"
                           "QSplitter::handle:vertical {\n"
                           "    height: 1px;\n"
                           "}\n"
                           "\n"
                           "QListWidget {\n"
                           "    background-color: silver;\n"
                           "    border-radius: 5px;\n"
                           "    margin-left: 5px;\n"
                           "}\n"
                           "\n"
                           "QListWidget::item {\n"
                           "    color: black;\n"
                           "}\n"
                           "\n"
                           "QMessageBox {\n"
                           "    messagebox-critical-icon    : url(:/dark_blue/img/critical.png);\n"
                           "    messagebox-information-icon    : url(:/dark_blue/img/information.png);\n"
                           "    messagebox-question-icon    : url(:/dark_blue/img/question.png);\n"
                           "    messagebox-warning-icon:    : url(:/dark_blue/img/warning.png);\n"
                           "}\n"
                           "\n"
                           "ColorButton::enabled {\n"
                           "    border-radius: 0px;\n"
                           "    border: 1px solid #444444;\n"
                           "}\n"
                           "\n"
                           "ColorButton::disabled {\n"
                           "    border-radius: 0px;\n"
                           "    border: 1px solid #AAAAAA;\n"
                           "}")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 40, 381, 20))
        self.lineEdit.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 40, 31, 21))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 90, 301, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 150, 81, 20))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 35, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 31, 16))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(100, 260, 411, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
                                       "    \n"
                                       "    rgb(179, 255, 179)\n"
                                       "\n"
                                       " border :1px sold;\n"
                                       "}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 170, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(230, 170, 81, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet(".QPushButton {\n"
                                      "  background: #1090e6;\n"
                                      "  background-image: -webkit-linear-gradient(top, #1090e6, #b6d0e0);\n"
                                      "  background-image: -moz-linear-gradient(top, #1090e6, #b6d0e0);\n"
                                      "  background-image: -ms-linear-gradient(top, #1090e6, #b6d0e0);\n"
                                      "  background-image: -o-linear-gradient(top, #1090e6, #b6d0e0);\n"
                                      "  background-image: linear-gradient(to bottom, #1090e6, #b6d0e0);\n"
                                      "  -webkit-border-radius: 60;\n"
                                      "  -moz-border-radius: 60;\n"
                                      "  border-radius: 60px;\n"
                                      "  font-family: Arial;\n"
                                      "  color: #ffffff;\n"
                                      "  padding: 10px;\n"
                                      "  border: solid #9ac9e6 2px;\n"
                                      "  text-decoration: none;\n"
                                      "}\n"
                                      "\n"
                                      ".QPushButton:hover {\n"
                                      "  background: #0fa34a;\n"
                                      "  background-image: -webkit-linear-gradient(top, #0fa34a, #fcfcfc);\n"
                                      "  background-image: -moz-linear-gradient(top, #0fa34a, #fcfcfc);\n"
                                      "  background-image: -ms-linear-gradient(top, #0fa34a, #fcfcfc);\n"
                                      "  background-image: -o-linear-gradient(top, #0fa34a, #fcfcfc);\n"
                                      "  background-image: linear-gradient(to bottom, #0fa34a, #fcfcfc);\n"
                                      "  text-decoration: none;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 90, 71, 21))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(100, 130, 81, 21))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        # self.comboBox.addItem("")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 170, 31, 21))
        self.lcdNumber.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(310, 170, 31, 21))
        self.lcdNumber_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(100, 220, 121, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 220, 131, 16))
        self.checkBox_2.setObjectName("checkBox_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # -----------my function------------------
        self.lineEdit.setText("Add URL")
        self.lineEdit_2.setText("storage location")
        self.lineEdit_3.setText("Add quality")
        self.handel_button(Form)
        self.handel_fin(Form)

        # ----------------------------------------

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dowonload Doyo"))
        self.label.setText(_translate("Form", "URL"))
        self.label_2.setText(_translate("Form", "Locition "))
        self.label_3.setText(_translate("Form", "QUaltiy"))
        # self.label_4.setText(_translate("Form", "Current Downloading File"))
        # self.label_5.setText(_translate("Form", "Playlist Video Number"))
        self.pushButton.setToolTip(_translate("Form",
                                              "<html><head/><body><p><span style=\" color:#ffffff;\">click to download</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Download"))
        self.pushButton_2.setText(_translate("Form", "borwse"))
        self.comboBox.setItemText(3, _translate("Form", "best quality"))
        self.comboBox.setItemText(1, _translate("Form", "360p"))
        self.comboBox.setItemText(0, _translate("Form", "less quality"))
        self.comboBox.setItemText(2, _translate("Form", "720p"))
        # self.comboBox.setItemText(4, _translate("Form", "144p"))

        self.checkBox.setText(_translate("Form", "Non vido"))
        # self.checkBox_2.setText(_translate("Form", "Close Programe After Dowwnload"))

    def handel_fin(self, From):
        self.lineEdit.setText("Add URL")
        self.lineEdit_2.setText("storage location")
        kk = "Add quality "
        self.lineEdit_3.setText(kk)

    def handel_button(self, From):
        self.pushButton.clicked.connect(
            self.download1)  # Since pressure goes to the download function  and pushbutton is button download
        self.pushButton_2.clicked.connect(self.handel_brose)

    def handel_brose(self):
        file_path, _ = QFileDialog.getSaveFileName()
        self.lineEdit_2.setText(file_path)

    def handel_progras(self, blocknum, blocksize, totalsize):
        try:
            # Check if the blocknum and blocksize are greater than 0
            # and if totalsize is greater than or equal to blocknum * blocksize
            if blocknum <= 0 or blocksize <= 0 or totalsize < blocknum * blocksize:
                raise ValueError("Invalid input values")

            # Calculate the percentage of completion
            percent_completed = blocknum * blocksize * 100 / totalsize
            self.progressBar.setValue(percent_completed)
            QApplication.processEvents()  # PROBLEM SYSTEM EXICTION

        except Exception as e:
            print(f"An error occurred: {e}")

    def download1(self):

        url = self.lineEdit.text()
        ql = self.comboBox.currentText()  # Retrieving an item from combobox .
        self.lineEdit_3.setText(ql)
        print(ql)

        save_loction = self.lineEdit_2.text()  # input loction save file

        try:
            # qualtiy vido 133 <=> 240p
            if url[12] == 'y':
                yt = YouTube(url)  # yt is varible
                if ql == '360p':
                    stream = yt.streams.get_by_itag(18)  # true
                elif ql == 'less quality':
                    stream=yt.streams.filter(progressive=True,file_extension="mp4").get_lowest_resolution()
                elif ql == '720p':
                    stream = yt.streams.get_by_itag(22)  # true
                else:
                    if (ql == 'best quality'):
                        stream=yt.streams.filter(progressive=True,file_extension="mp4").get_highest_resolution()
                stream.download(save_loction)
            else:
                urllib.request.urlretrieve(url, save_loction, self.handel_progras)
        except Exception:
            msg = QMessageBox()
            msg.setText("ERROR")
            msg.exec()
            return

        msg = QMessageBox()  # MESSAGE BOX IN PYSIDE6
        msg.setText("Loading finished ....")
        msg.exec()
        self.progressBar.setValue(0)
        self.lineEdit.setText('')
        self.lineEdit_2.setText('')

        '''
        yt = YouTube(url)     #yt is varible
        stream = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
        stream.download(filename=save_loction,on_progress_callback=handel_progras)'''

    def combo_box_changed(self):
        pass
        # Update the label with the selected option
        # self.lineEdit_3.setText(self.checkBox.currentText())


if __name__ == "__main__":
    import sys
    import os
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
